name: Bilibili-Story-Builder Testing

on:
  push:
    branches:
      - main
      - githubActions-testRun

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: openApiPort-Testing
        run: node dist/test/openApiPort-Test.js

      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get install openvpn -y
        shell: bash
      
      - name: OpenVPN Connect
        run: |
          echo "${{ secrets.VPN_CONFIG }}" > vpn-config.ovpn
          echo "${{ secrets.VPN_CREDENTIALS }}" > vpn-credentials.txt
          sudo openvpn --config vpn-config.ovpn --auth-user-pass vpn-credentials.txt --daemon
        shell: bashs
      
      - name: main-Test
        run: node dist/test/main-Test.js
