name: Bilibili-Story-Builder Testing

on:
  push:
    branches:
      - main
      - githubActions-testRun

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: openApiPort-Testing
        run: node dist/test/openApiPort-Test.js

      - name: Install OpenVPN
        run: |
          sudo apt-get update
          sudo apt-get install openvpn -y
        shell: bash

      - name: Create VPN Credentials Files
        run: |
          echo -n "${{ secrets.VPN_USERNAME }}" > vpn-username.txt
          echo -n "${{ secrets.VPN_PASSWORD }}" > vpn-password.txt
          chmod 600 vpn-username.txt vpn-password.txt
      
      - name: OpenVPN Connect
        run: |
          sudo openvpn --config vpn-config.ovpn --auth-user-pass vpn-credentials.txt --daemon
        shell: bash

      - name: main-Test
        run: node dist/test/main-Test.js
