name: Bilibili-Story-Builder Testing

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.0

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build
      
      - name: Turn Off API Proxy
        run: node src/test/turn-off-apiProxy.js
        env:
          CLOUDFLARE_TENSORMIK_ZONE_ID: ${{ secrets.CLOUDFLARE_TENSORMIK_ZONE_ID }}
          CLOUDFLARE_GLOBAL_KEY: ${{ secrets.CLOUDFLARE_GLOBAL_KEY }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}

      - name: openApiPort-Testing
        run: node dist/test/openApiPort-Test.js

      - name: main-Testing
        run: node dist/test/main-Test.js
      
      - name: outsideAPI-Testing
        run: node dist/test/outside-api-test.js
      
      - name: Turn On API Proxy
        run: node src/test/turn-on-apiProxy.js
        env:
          CLOUDFLARE_TENSORMIK_ZONE_ID: ${{ secrets.CLOUDFLARE_TENSORMIK_ZONE_ID }}
          CLOUDFLARE_GLOBAL_KEY: ${{ secrets.CLOUDFLARE_GLOBAL_KEY }}
          CLOUDFLARE_EMAIL: ${{ secrets.CLOUDFLARE_EMAIL }}